import { defineStore } from 'pinia';

export const useMetadataStore = defineStore({
  id: 'metadata',
  state: () => ({
    defaultMetadata: {
      charset: 'utf-8',
      xUaCompatible: 'IE=edge',
      ogLocale: 'en_US',
      viewport: 'width=device-width,initial-scale=1.0',
      title: 'outbreak.info SARS-CoV-2 data explorer',
      description: 'Outbreak.info explores COVID-19 and SARS-CoV-2 data with variant surveillance reports, data on cases and deaths, and a searchable research library.',
      ogUrl: 'https://outbreak.info/',
      ogSiteName: 'outbreak.info',
      ogTitle: 'outbreak.info SARS-CoV-2 data explorer',
      ogImage: 'https://i.postimg.cc/d0NwNjjs/featured-copy.jpg',
      ogImageType: 'image/jpg',
      ogImageWidth: '1200',
      ogImageHeight: '630',
      ogType: 'website',
      ogDescription: 'Outbreak.info explores COVID-19 and SARS-CoV-2 data with variant surveillance reports, data on cases and deaths, and a searchable research library.',
      fbApp_id: '',
      twitterTitle: 'outbreak.info SARS-CoV-2 data explorer',
      twitterImage: 'https://i.postimg.cc/d0NwNjjs/featured-copy.jpg',
      twitterDescription: 'Outbreak.info explores COVID-19 and SARS-CoV-2 data with variant surveillance reports, data on cases and deaths, and a searchable research library.',
      twitterUrl: 'https://outbreak.info/',
      twitterCard: '',
      msapplicationTileColor: '#126b93',
      msapplicationConfig: '@/assets/browserconfig.xml',
      themeColor: '#ffffff',
    },
    resourceSummaryMetadata: {
      title: 'COVID-19 Research Library',
      description: 'Find and access COVID-19 research including journal articles, preprints, clinical trials, datasets, protocols, and more using the Outbreak.info Research Library.',
      ogTitle: 'COVID-19 Research Library',
      ogDescription: 'Find and access COVID-19 research including journal articles, preprints, clinical trials, datasets, protocols, and more using the Outbreak.info Research Library.',
      twitterTitle: 'COVID-19 Research Library',
      twitterDescription: 'Find and access COVID-19 research including journal articles, preprints, clinical trials, datasets, protocols, and more using the Outbreak.info Research Library.',
      keywords: 'covid-19, sars-cov-2, variants, journal articles, clinical trials, medical journals, search, biomedical, research, database, javascript',
    },
    resourceMetadata: {
      title: 'COVID-19 Research Library | Search',
      description: 'Search results for COVID-19 research aggregated by the Outbreak.info Research Library.',
      ogTitle: 'COVID-19 Research Library | Search',
      ogDescription: 'Search results for COVID-19 research aggregated by the Outbreak.info Research Library.',
      twitterTitle: 'COVID-19 Research Library | Search',
      twitterDescription: 'Search results for COVID-19 research aggregated by the Outbreak.info Research Library.',
      keywords: '',
    },
  }),
  getters: {},
  actions: {},
});